### ISSUE TITLE
CHANGE servername to sylius.local

### ISSUE THREAD

**Issue by mfuehrer82** [Sylius/Vagrant#16]
Chrome 63 (out since December 2017), will force all domains ending on .dev (and .foo) to be redirected to HTTPS via a preloaded HTTP Strict Transport Security (HSTS) header.

**Comment by jackbentley** [comment]
Preferably it should be something that's specified as reserved in the RFC? - https://tools.ietf.org/html/rfc2606

Personally, I've adopted `.test` for all my projects.
